/*
Additional required concepts that do not have elements in the data dictionary
*/
library ANCBaseConcepts

valueset "Antenatal care case": 'http://fhir.org/guides/who/anc-cds/ValueSet/antenatal-care-case'
valueset "Antenatal care contact": 'http://fhir.org/guides/who/anc-cds/ValueSet/antenatal-care-contact'
//valueset "Pregnancy expected delivery date method": 'http://hl7.org/fhir/uv/ips/ValueSet/edd-method-uv-ips'
//valueset "Pregnancy status": 'http://fhir.org/guides/who/anc-cds/ValueSet/pregnancy-status'
//valueset "Pregnancy status - pregnant": 'http://fhir.org/guides/who/anc-cds/ValueSet/pregnancy-status-pregnant'



valueset "Pregnancy condition": 'http://fhir.org/guides/who/anc-cds/ValueSet/pregnancy-condition'
//valueset "Gestational age from ultrasound": 'http://fhir.org/guides/who/anc-cds/ValueSet/gestational-age-from-ultrasound'

// TODO: Add these to the dictionary to generate, shouldn't need to do these manually


valueset "Iron supplement": 'http://fhir.org/guides/who/anc-cds/ValueSet/iron-supplement'
valueset "Folic acid supplement": 'http://fhir.org/guides/who/anc-cds/ValueSet/folic-acid-supplement'