name: "common machine setup"
description: "Prepares the machine"
runs:
  using: "composite"
  steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: "11"
    - name: Make files executable
      shell: bash
      run: chmod +x ./gradlew && chmod +x ./engine/checksum.sh

#    - name: Copy CI gradle.properties
#      shell: bash
#      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
    - name: "Setup Gradle"
      uses: gradle/gradle-build-action@v2
      with:
        # Don't reuse cache entries from any other Job.
        gradle-home-cache-strict-match: true
        # we may want to remove this so it is only set to false for main branch.
        cache-read-only: false
        # Limit the size of the cache entry.
        # These directories contain instrumented/transformed dependency jars which can be reconstructed relatively quickly.
        gradle-home-cache-excludes: |
          caches/jars-9
          caches/transforms-3
