name: "common machine setup"
description: "Prepares the machine"
runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: "17"
    - name: Make files executable
      shell: bash
      run: chmod +x ./gradlew

    - name: "Setup Gradle"
      uses: gradle/gradle-build-action@v2
      with:
        # Limit the size of the cache entry.
        # These directories contain instrumented/transformed dependency jars which can be reconstructed relatively quickly.
        gradle-home-cache-excludes: |
          caches/jars-9
          caches/transforms-3
